import { itDepartments, itJobTitles } from './itData';

export const initialMockUsers = [
  { id: 'adminSim001', name: 'Admin', email: 'admin@progress.com', password: 'admin123', profile: 'admin', department: itDepartments[1], jobTitle: itJobTitles[itDepartments[1]][2], status: 'active', lastLogin: '2025-06-03T10:00:00Z', createdAt: '2023-01-15T00:00:00Z', roleDescription: 'Admin' },
  { id: 'gestorSim002', name: 'Bruno Gestor', email: 'bruno.gestor@progress.com', password: 'gestor123', profile: 'manager', department: itDepartments[0], jobTitle: "Gerente de Engenharia", status: 'active', lastLogin: '2025-06-04T14:30:00Z', createdAt: '2023-02-20T00:00:00Z', roleDescription: 'Gestor' },
  { id: 'colabSim003', name: 'Carlos Dev', email: 'colab.carlos@progress.com', password: 'colab123', profile: 'collaborator', department: itDepartments[0], jobTitle: itJobTitles[itDepartments[0]][1], managerId: 'gestorSim002', status: 'active', lastLogin: '2025-06-05T08:15:00Z', createdAt: '2023-03-10T00:00:00Z', roleDescription: 'Colaborador' },
  { id: 'user004', name: 'Diana Designer', email: 'diana.designer@example.com', password: 'diana123', profile: 'collaborator', department: itDepartments[8], jobTitle: itJobTitles[itDepartments[8]][0], managerId: 'gestorSim005', status: 'active', lastLogin: '2025-06-02T11:00:00Z', createdAt: '2023-04-01T00:00:00Z', roleDescription: 'Colaborador' },
  { id: 'gestorSim005', name: 'Eduardo Líder UX', email: 'eduardo.lider@example.com', password: 'eduardo123', profile: 'manager', department: itDepartments[8], jobTitle: "Líder de Design", status: 'active', lastLogin: '2025-06-01T16:20:00Z', createdAt: '2023-01-25T00:00:00Z', roleDescription: 'Gestor' },
];

export const initialMockPDIs = [
  { id: 'pdi001', title: 'Dominar React Avançado', overallDescription: 'Aprofundar conhecimentos em React para desenvolvimento de interfaces complexas e performáticas.', collaboratorId: 'colabSim003', managerId: 'gestorSim002', status: 'Em Andamento', startDate: '2025-03-15T00:00:00Z', dueDate: '2025-09-15T00:00:00Z', department: itDepartments[0], priority: 'Alta', objectives: [{ id: 'obj1_pdi001', text: 'Concluir curso de React Hooks avançados e Context API.', status: 'concluido', activityType: "Curso Online", estimatedDurationDays: 30 }, { id: 'obj2_pdi001', text: 'Aplicar técnicas de otimização (memo, lazy loading) em projeto existente.', status: 'em_andamento', activityType: "Projeto Prático", estimatedDurationDays: 45 }, { id: 'obj3_pdi001', text: 'Desenvolver um componente reutilizável com TDD.', status: 'pendente', activityType: "Projeto Prático", estimatedDurationDays: 30 },], progress: 33 },
  { id: 'pdi002', title: 'Aprimorar UX para Carrinho de Compras', overallDescription: 'Melhorar a experiência do usuário no fluxo de checkout do e-commerce.', collaboratorId: 'user004', managerId: 'gestorSim005', status: 'Em Andamento', startDate: '2025-05-01T00:00:00Z', dueDate: '2025-08-01T00:00:00Z', department: itDepartments[8], priority: 'Alta', objectives: [{ id: 'obj1_pdi002', text: 'Realizar 5 entrevistas com usuários para identificar pontos de dor.', status: 'em_andamento', activityType: "Pesquisa com Usuário", estimatedDurationDays: 15 }, { id: 'obj2_pdi002', text: 'Criar protótipos de baixa e alta fidelidade para 3 novas soluções de checkout.', status: 'pendente', activityType: "Prototipagem", estimatedDurationDays: 30 }, { id: 'obj3_pdi002', text: 'Conduzir testes de usabilidade com os protótipos.', status: 'pendente', activityType: "Teste de Usabilidade", estimatedDurationDays: 20 },], progress: 0 },
  { id: 'pdi003', title: 'Planejamento Estratégico Q3 2025', overallDescription: 'Definir metas e roadmap para o time de Frontend no terceiro trimestre.', collaboratorId: 'gestorSim002', managerId: 'adminSim001', status: 'Pendente', startDate: '2025-07-01T00:00:00Z', dueDate: '2025-07-15T00:00:00Z', department: itDepartments[0], priority: 'Alta', objectives: [{ id: 'obj1_pdi003', text: 'Analisar métricas de performance do Q2.', status: 'pendente', activityType: "Análise de Dados", estimatedDurationDays: 5 }, { id: 'obj2_pdi003', text: 'Conduzir reunião de brainstorming com a equipe.', status: 'pendente', activityType: "Reunião", estimatedDurationDays: 1 }, { id: 'obj3_pdi003', text: 'Apresentar o plano para a diretoria.', status: 'pendente', activityType: "Apresentação", estimatedDurationDays: 2 },], progress: 0 },
];

export const initialMockFeedbacks = [
  { id: 'fb001', pdiId: 'pdi001', collaboratorId: 'colabSim003', managerId: 'gestorSim002', feedbackText: 'Carlos, seu progresso no curso de React está ótimo! Continue focado nos próximos módulos sobre Context API.', dateSubmitted: '2025-05-20T10:00:00Z', type: 'Positivo', meetingDate: '2025-05-19T00:00:00Z', nextSteps: 'Agendar revisão do projeto prático em 2 semanas.' },
  { id: 'fb002', pdiId: null, collaboratorId: 'user004', managerId: 'gestorSim005', feedbackText: 'Diana, sua apresentação sobre as heurísticas de Nielsen foi excelente. Muito clara e bem estruturada!', dateSubmitted: '2025-04-08T14:30:00Z', type: 'Reconhecimento', meetingDate: '2025-04-07T00:00:00Z' },
];
